version: '3.3'

services:
  tyk:
    container_name: "tyk"
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config/mongodb.yml:/opt/tyk-gateway/mongodb.yml:ro
    networks:
      - tyk

  redis:
    image: redis:4.0-alpine
    ports:
    - 6379:6379
    command: redis-server --appendonly yes
    networks:
      - tyk

  mongo:
    container_name: mongo
    image: mongo:4.0
    command: [ "mongod", "--smallfiles" ]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: tyk_analytics
    volumes:
      - db-data:/data/db
    networks:
      - tyk

volumes:
  db-data:

networks:
  tyk: